### ISSUE TITLE
fatal error exe is not defined

### ISSUE THREAD

**Issue by Jimbo4350** [seek-oss/serverless-haskell#113]
I have written a simple `servant` server and converted it into a lambda function that queries a `MySQL` db in amazon RDS. I can get it to work locally with `serverless offline start` however when I deploy it (`serverless deploy`) I get the following error in my dashboard when trying to access my simple test endpoint.

```
10:24:00 am
START RequestId: 9577f510-712c-4204-b9ac-05d75defcb42 Version: $LATEST
10:24:00 am
2019-10-28T14:24:00.167Z	9577f510-712c-4204-b9ac-05d75defcb42	INFO	
10:24:00 am
2019-10-28T14:24:00.169Z	9577f510-712c-4204-b9ac-05d75defcb42	ERROR	ReferenceError: exe is not defined
    at Object.<anonymous> (/var/task/s_apigw.js:14:66)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at _tryRequire (/var/runtime/UserFunction.js:75:12)
    at _loadUserApp (/var/runtime/UserFunction.js:95:12)
10:24:00 am
2019-10-28T14:24:00.185Z	9577f510-712c-4204-b9ac-05d75defcb42	ERROR	Invoke Error	{
    "errorType": "ReferenceError",
    "errorMessage": "exe is not defined",
    "stack": [
        "ReferenceError: exe is not defined",
        "    at Object.<anonymous> (/var/task/s_apigw.js:14:66)",
        "    at Module._compile (internal/modules/cjs/loader.js:778:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)",
        "    at Module.load (internal/modules/cjs/loader.js:653:32)",
        "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)",
        "    at Module.require (internal/modules/cjs/loader.js:692:17)",
        "    at require (internal/modules/cjs/helpers.js:25:18)",
        "    at _tryRequire (/var/runtime/UserFunction.js:75:12)",
        "    at _loadUserApp (/var/runtime/UserFunction.js:95:12)"
    ]
}
10:24:00 am
END RequestId: 9577f510-712c-4204-b9ac-05d75defcb42
10:24:00 am
REPORT RequestId: 9577f510-712c-4204-b9ac-05d75defcb42	Duration: 30.73 ms	Billed Duration: 100 ms	Memory Size: 1024 MB	Max Memory Used: 83 MB	Init Duration: 210.80 ms	
```

**Comment by koterpillar** [comment]
Can you please share your `serverless.yml`?

**Comment by Jimbo4350** [comment]
@koterpillar 
```
org: jimbo4350
app: minimal-example-rds
service: serverless-minimal-example-rds

provider:
  name: aws
  runtime: haskell
  region: ap-southeast-2
  timeout: 100

functions:
  apigw:
    handler: serverless-haskell-example.api-exe
    events:
      - http:
          path: item/test
          method: get

plugins:
  - serverless-haskell
  - serverless-offline
```
