### ISSUE TITLE
Error: child process output bad JSON

### ISSUE THREAD

**Issue by Jimbo4350** [seek-oss/serverless-haskell#118]
I'm currently getting this error from my AWS apigateway api using Postman:

```
{
    "errorType": "Error",
    "errorMessage": "child process output bad JSON: ",
    "stack": [
        "Error: child process output bad JSON: ",
        "    at _homogeneousError (/var/runtime/CallbackContext.js:13:12)",
        "    at postError (/var/runtime/CallbackContext.js:30:51)",
        "    at done (/var/runtime/CallbackContext.js:57:7)",
        "    at fail (/var/runtime/CallbackContext.js:69:7)",
        "    at /var/runtime/CallbackContext.js:105:16",
        "    at process._tickCallback (internal/process/next_tick.js:68:7)"
    ]
```
My json payload is as follows:
```
{ "resource" : "/updatepic"
, "body" : "pleasework"}
```
My end point is: `https://xxxxxxxxx.execute-api.us-east-1.amazonaws.com/dev/updatepic`

I'm not sure if I'm formatting my JSON payload correctly. I've tried many variations but I'm getting timeouts and the bad JSON error above.

If I don't put any payload in my POST request my lamba function continues to execution and outputs "not enough input"/

This is my "event" JSON parser:
```
instance FromJSON Event where
  parseJSON = withObject "Event" $ \v -> do
    bd <- v .: "body"
    rs <- v .: "resource"
    pure $ Event bd rs
```

And this is my `serverless.yml`
```
service: hailmeout-production

provider:
  name: aws
  runtime: haskell
  region: us-east-1
  timeout: 30

functions:
  servantserver:
    handler: servantBackend.backend
    events:
      - http:
          path: updatepic
          method: post
          cors: true

plugins:
  - serverless-haskell
  - serverless-offline
```
