### ISSUE TITLE
Offline even with `--useDocker` tries to use lambci/lambda:haskell which doesn't exist

### ISSUE THREAD

**Issue by danwdart** [seek-oss/serverless-haskell#138]
```
offline: Warning: found unsupported runtime 'haskell' for function 'emailme'
No valid trust data for haskell
offline: Failure: Command failed with exit code 1: docker pull --disable-content-trust=false lambci/lambda:haskell
No valid trust data for haskell
Error: Command failed with exit code 1: docker pull --disable-content-trust=false lambci/lambda:haskell
No valid trust data for haskell
    at makeError (/home/dwd/code/mine/projects/haskell/slsdemo/node_modules/serverless-offline/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/dwd/code/mine/projects/haskell/slsdemo/node_modules/serverless-offline/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Function._pullImage (/home/dwd/code/mine/projects/haskell/slsdemo/node_modules/serverless-offline/dist/lambda/handler-runner/docker-runner/DockerImage.js:35:7)
```

Tried to use `provided` as runtime but I just get:
```
offline: [502] {"errorType":"exitError","errorMessage":"RequestId: 2cf06505-d533-17c1-57a0-edde6a345edc Error: Couldn't find valid bootstrap(s): [/var/task/bootstrap /opt/bootstrap]"}
```

Any ideas?

**Comment by koterpillar** [comment]
Can you please share your `serverless.yml`? This is being tested in the integration tests (https://github.com/seek-oss/serverless-haskell/blob/master/integration-test/skeleton/serverless.yml, https://github.com/seek-oss/serverless-haskell/blob/master/integration-test/run.sh#L162-L172).

**Comment by seanhess** [comment]
@danwdart I'm getting this same error while trying to get serverless-offline to work. I'm testing the route in the browser by visiting http://localhost:3000/dev/value

Error
```
$ sls offline --useDocker
offline: Starting Offline: dev/us-east-1.
offline: Offline [http for lambda] listening on http://localhost:3002

   ┌─────────────────────────────────────────────────────────────────────────────┐
   │                                                                             │
   │   GET | http://localhost:3000/dev/value                                     │
   │   POST | http://localhost:3000/2015-03-31/functions/get-value/invocations   │
   │                                                                             │
   └─────────────────────────────────────────────────────────────────────────────┘

offline: [HTTP] server ready: http://localhost:3000 🚀
offline:
offline: Enter "rp" to replay the last request

offline: GET /dev/value (λ: get-value)

offline: Warning: found unsupported runtime 'haskell' for function 'get-value'
No valid trust data for haskell
offline: Failure: Command failed with exit code 1: docker pull --disable-content-trust=false lambci/lambda:haskell
No valid trust data for haskell
Error: Command failed with exit code 1: docker pull --disable-content-trust=false lambci/lambda:haskell
No valid trust data for haskell
```


Serverless.yaml

```
service: demo

provider:
  name: aws
  runtime: haskell

functions:
  get-value:
    handler: server.get-value
    events:
      - http:
          path: value
          method: get

    # Here, mypackage is the Haskell package name and myfunc is the executable
    # name as defined in the Cabal file. The handler field may be prefixed
    # with a path of the form `dir1/.../dirn`, relative to `serverless.yml`,
    # which points to the location where the Haskell package `mypackage` is
    # defined. This prefix is not needed when the Stack project is defined at
    # the same level as `serverless.yml`.

plugins:
  - serverless-haskell
  - serverless-offline

```
