### ISSUE TITLE
Permission errors

### ISSUE THREAD

**Issue by danwdart** [seek-oss/serverless-haskell#156]
`/var/task` is owned by `aws_user:1000` now, but `lambci/lambda:build-provided.al2` runs as `sbx_user1051`, which makes `sls offline start` die with permission errors like not being able to access `/var/task`.

How can this be rectified?

Using sls yaml config:

```
plugins:
  - serverless-haskell
  - serverless-offline

custom:
  haskell:
    docker: true
  serverless-offline:
    useDocker: true
    printOutput: true
```

Ta!
