### ISSUE TITLE
Could not find serverless-haskell in stack's dependencies

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [seek-oss/serverless-haskell#68]
Trying to go through your readme and when I get to `sls deploy` I receive the following error message:
```shell
> npx sls deploy
Pulling image from registry: 'fpco/stack-build:lts-12.9'
lts-12.9: Pulling from fpco/stack-build
Digest: sha256:fdbabc6df1135ab640041c966a2f8ced3bdaff7226de4a41f52d8c08fc9d64c7
Status: Image is up to date for fpco/stack-build:lts-12.9
Serverless: Could not find serverless-haskell in stack's dependencies. Make sure serverless-haskell you are using LTS 12 (or newer), or add it as an extra-dep in your stack.yaml.

  Error --------------------------------------------------

  Package not found.

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.11.3
     Serverless Version:     1.31.0
```

I have added the following to my stack.yaml file
```yaml
extra-deps:
- serverless-haskell-0.7.5
```

I'm sure that this is something easy that I'm missing

**Comment by koterpillar** [comment]
Can you please show your `serverless.yml` and the output of `stack ls dependencies`?

**Comment by BebeSparkelSparkel** [comment]
```
> stack ls dependencies
awsLambda 0.1.0.0
base 4.11.1.0
ghc-prim 0.5.2.0
integer-gmp 1.0.2.0
rts 1.0
```

```yaml
# This file was automatically generated by 'stack init'
#
# Some commonly used options have been documented as comments in this file.
# For advanced use and comprehensive documentation of the format, please see:
# https://docs.haskellstack.org/en/stable/yaml_configuration/

# Resolver to choose a 'specific' stackage snapshot or a compiler version.
# A snapshot resolver dictates the compiler version and the set of packages
# to be used for project dependencies. For example:
#
# resolver: lts-3.5
# resolver: nightly-2015-09-21
# resolver: ghc-7.10.2
# resolver: ghcjs-0.1.0_ghc-7.10.2
#
# The location of a snapshot can be provided as a file or url. Stack assumes
# a snapshot provided as a file might change, whereas a url resource does not.
#
# resolver: ./custom-snapshot.yaml
# resolver: https://example.com/snapshots/2018-01-01.yaml
resolver: lts-12.9

# User packages to be built.
# Various formats can be used as shown in the example below.
#
# packages:
# - some-directory
# - https://example.com/foo/bar/baz-0.0.2.tar.gz
# - location:
#    git: https://github.com/commercialhaskell/stack.git
#    commit: e7b331f14bcffb8367cd58fbfc8b40ec7642100a
# - location: https://github.com/commercialhaskell/stack/commit/e7b331f14bcffb8367cd58fbfc8b40ec7642100a
#  subdirs:
#  - auto-update
#  - wai
packages:
- .
# Dependency packages to be pulled from upstream that are not in the resolver
# using the same syntax as the packages field.
# (e.g., acme-missiles-0.3)
extra-deps:
- serverless-haskell-0.7.5

# Override default flag values for local packages and extra-deps
# flags: {}

# Extra package databases containing global packages
# extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true
#
# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: ">=1.7"
#
# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64
#
# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
#
# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
```
